[tool.poetry]
name = "galaxy"
version = "21.01"
description = "Galaxy is an open, web-based platform for accessible, reproducible, and transparent computational research."
authors = ["Galaxy Contributors"]
license = "AFL-3.0"
readme = "README.rst"
homepage = "https://galaxyproject.org/"
repository = "https://github.com/galaxyproject/galaxy/"
documentation = "https://docs.galaxyproject.org/"

[[tool.poetry.source]]
name = "galaxyproject"
url = "https://wheels.galaxyproject.org/simple"

[tool.poetry.dependencies]
aiofiles = "*"
alembic = "*"
async-generator = {version = "*", python = "~3.6"}
async-exit-stack = {version = "*", python = "~3.6"}
Babel = "*"
bdbag = "*"
Beaker = "1.11.0"
bioblend = "*"
bleach = "*"
boltons = "*"
boto = "*"
bx-python = "*"
Cheetah3 = "*"
cloudauthz = "==0.6.0"
cloudbridge = "*"
cwltool = "==3.0.20201109103151"
dictobj = "*"
docutils = "*"
Fabric3 = "*"
fastapi = "*"
fastapi-utils = "*"
future = "*"
galaxy_sequence_utils = "*"
gxformat2 = "*"
h5py = "!=2.7.0, !=2.7.1"
isa-rwval = "*"
kombu = "*"
Mako = "*"
Markdown = "*"
MarkupSafe = "*"
Mercurial = "*"
nodeenv = "*"
nose = "*"
numpy = "*"
paramiko = "*"
Parsley = "*"
Paste = "*"
psutil = "*"
pulsar-galaxy-lib = "==0.14.2"
pycryptodome = "*"
pykwalify = "*"
pyparsing = "*"
pysam = "*"
python = "^3.6"
pyuwsgi = "*"
PyYAML = "*"
refgenconf = ">=0.7.0"
requests = "*"
Routes = "*"
social-auth-core = {version = "==3.3.0", extras = ["openidconnect"]}
sortedcontainers = "*"
SQLAlchemy = "*"
sqlalchemy-migrate = "*"
SQLAlchemy-Utils = "!=0.36.8"  # https://github.com/kvesteri/sqlalchemy-utils/issues/462
sqlitedict = "*"
sqlparse = "*"
svgwrite = "*"
uvicorn = "*"
WebOb = "*"
Whoosh = "*"
zipstream-new = "*"

[tool.poetry.dev-dependencies]
gunicorn = "*"
lxml = "!=4.2.2"
markdown-it-reporter = "*"
NoseHTML = "*"
pygithub = "*"
pytest = "*"
pytest-cov = "*"
pytest-html = "*"
python-irodsclient = "*"
pytest-json-report = "*"
pytest-mock = "*"
pytest-pythonpath = "*"
pytest-postgresql = "*"
pytest-shard = "*"
recommonmark = "*"
responses = "*"
selenium = "*"
Sphinx = "*"
sphinx_markdown_tables = "*"
sphinx_rtd_theme = "*"
statsd = "*"
testfixtures = "*"
twill = "*"
watchdog = "*"
