# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Feb 28 08:28:34 2019
# ------------------------------------------------

package:
    name: python
    version: 3.6.7
source:
    -   patches:
            - 0002-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
            - 0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - 0004-Win32-distutils-Also-look-for-executable.bat.patch
            - 0005-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch
            - 0006-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - 0007-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - 0008-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - 0009-Support-cross-compiling-byte-code.patch
            - 0010-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - 0011-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - 0012-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - 0013-Win32-Do-not-download-externals.patch
            - 0014-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - 0015-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - 0016-Disable-new-dtags-in-unixccompiler.py.patch
            - 0017-Fix-cross-compilation-on-Debian-based-distros.patch
        sha256: 81fd1401a9d66533b0a3e9e3f4ea1c7c6702d57d5b90d659f971e6f1b745f77d
        url: https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tar.xz
build:
    ignore_run_exports:
        - bzip2
        - libgcc-ng
    no_link:
        - bin/python3.6
    number: '1004'
    string: h381d211_1004
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - make 4.2.1 h14c3975_2004
        - pkg-config 0.29.2 h14c3975_1004
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2018.11.29 ha4d7672_0
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1a h14c3975_1000
        - readline 7.0 hf8c457e_1001
        - sqlite 3.26.0 h67949de_1000
        - tk 8.6.9 h84994c4_1000
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - libffi >=3.2.1,<3.3.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - ncurses >=6.1,<6.2.0a0
        - openssl >=1.1.1a,<1.1.2a
        - readline >=7.0,<8.0a0
        - sqlite >=3.26.0,<4.0a0
        - tk >=8.6.9,<8.7.0a0
        - xz >=5.2.4,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
            python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - python -c "import sys; files = [f for f in sys.argv[2:] if ' -partition=none'
            in open(f, 'r').read()]; assert len(files) == 0, files" ${PREFIX}/lib/*/*.py
        - test -f ${PREFIX}/lib/libpython3.6m.so
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
