# This file created by conda-build 3.18.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun  4 14:17:03 2019
# ------------------------------------------------

package:
    name: pip
    version: 19.1.1
source:
    sha256: 44d3d7d3d30a1eb65c7e5ff1173cdf8f7467850605ac7cc3707b6064bddd0958
    url: https://pypi.io/packages/source/p/pip/pip-19.1.1.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal:main
    number: '0'
    string: py36_0
requirements:
    host:
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py36_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - python 3.6.7 h381d211_1004
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.1 py36_0
        - sqlite 3.28.0 h8b20d00_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - python >=3.6,<3.7.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
