# This file created by conda-build 3.14.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Sep 13 19:56:18 2018
# ------------------------------------------------

package:
    name: readline
    version: '7.0'
source:
    patches:
        - patches/readline70-001
        - patches/readline70-002
        - patches/readline70-003
        - patches/readline70-004
        - patches/readline70-005
    sha256: 750d437185286f40a369e1e4f4764eda932b9459b5ec9a731628393dd3d32334
    url: ftp://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz
build:
    number: '1001'
    run_exports:
        - readline >=7.0,<8.0a0
    string: hf8c457e_1001
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - pkg-config 0.29.2 h14c3975_1003
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1001
    run:
        - libgcc-ng >=7.3.0
        - ncurses >=6.1,<6.2.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libreadline.a
        - test -f ${PREFIX}/lib/libreadline${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libhistory.a
        - test -f ${PREFIX}/lib/libhistory${SHLIB_EXT}
about:
    home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
    license: GPL-3.0
    license_file: COPYING
    summary: library for editing command lines as they are typed in
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - croth1
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - msarahan
        - ocefpaf
        - pelson
