name: Update dependencies
on: [push]  # TODO remove this
# TODO
#  schedule:
#    - cron: '0 3 * * 6'  # Run every saturday at 3 am.
jobs:
  update_dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip dir
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
      - name: Update dependencies
        run: python -m pip install --upgrade pip setuptools poetry
        run: python -m pip install -r lib/galaxy/dependencies/lint-requirements.txt
        run: python -m pip freeze -l > lib/galaxy/dependencies/pinned-lint-requirements.txt
        run: poetry update -v --lock
        run: poetry export -f requirements.txt --without-hashes --output lib/galaxy/dependencies/pinned-requirements.txt
        run: poetry export --dev -f requirements.txt --without-hashes --output lib/galaxy/dependencies/dev-requirements.txt

        #        run: make update-dependencies
        #      - name: Create pull request
        #        uses: peter-evans/create-pull-request@v3
        #        with:
        #          commit-message: Update dependencies
        #          title: Update dependencies
        #          body: Run make update-dependencies
        #          branch: dev_auto_update_dependencies
        #          delete-branch: true
        #          labels: area/dependencies
        #          token: ${{ secrets.GITHUB_TOKEN }}  # TODO remove this
